version: '3'
services:
  db: 
    image: "microsoft/mssql-server-linux:2017-latest"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      # note that password only has one dollar sign -- two here actually denotes
      # one since a single dollar sign would otherwise indicate variable interpolation
      SA_PASSWORD: ABcd12#$$
      MSSQL_PID: Express

  essbase:
    depends_on: 
      - db
    build: .
    image: appliedolap/essbase:11.1.2.4
    container_name: essbase
    ports:
      - "7001"
      - "9000"
      - "9443"
      #- "1423"
      #- "32768-33768"
    ulimits:
      nofile:
        hard: 32000
        soft: 10000

    environment:
      # There are some password requirements for various components; don't attempt to just set "password" here -- 
      # it'll cause configuration to fail
      # EPM_ADMIN: admin
      EPM_PASSWORD: password1
      NO_CONFIG: "false"

