version: '3'
services:
  db: 
    image: "microsoft/mssql-server-linux:2017-latest"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      # careful with passwords containing $ -- use $$ to indicate single $
      SA_PASSWORD: AAbb11##
      MSSQL_PID: Express

  essbase:
    depends_on: 
      - db
    build: .
    image: appliedolap/essbase:11.1.2.4
    container_name: essbase
    ports:
      - "7001:7001"
      - "9000:9000"
      - "9443:9443"
      - "1423:1423"
      - "32768-32778:32768-32778"
    ulimits:
      nofile:
        hard: 32000
        soft: 10000

    environment:
      # There are some password requirements for various components; don't attempt to just set "password" here -- 
      # it'll cause configuration to fail
      # EPM_ADMIN: admin
      EPM_PASSWORD: password1
      SQL_HOST: db
      SQL_USER: sa
      SQL_PASSWORD: AAbb11##
      #    hostname: docker1
